version: '3.8'

services:
  db:
    image: ankane/pgvector:v0.5.1
    container_name: customs_vector_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: customs_vectors
    ports:
      - "5432:5432"
    volumes:
      - pgvector-data:/var/lib/postgresql/data

volumes:
  pgvector-data:
